spring:
  application:
    name: aggregator

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        acks: all
        linger.ms: 5
        batch.size: 16384
        buffer.memory: 33554432

    consumer:
      group-id: aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.deserializer.SensorEventDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100

aggregator:
  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO